export const AVATARS = {
  CAPTAIN: {
    id: 'captain',
    name: 'The Captain',
    description: 'Bold and adventurous - leads the voyage through litigation',
    calmVideo: require('../../assets/avatars/captain/captain-calm.mp4'),
    actionVideo: require('../../assets/avatars/captain/captain-action.mp4'),
    thumbnail: require('../../assets/avatars/captain/captain-thumbnail.png'),
    primaryColor: '#1E40AF',
    accentColor: '#60A5FA',
  },
  NAVIGATOR: {
    id: 'navigator',
    name: 'The Navigator',
    description: 'Strategic and precise - charts the course to victory',
    calmVideo: require('../../assets/avatars/navigator/navigator-calm.mp4'),
    actionVideo: require('../../assets/avatars/navigator/navigator-action.mp4'),
    thumbnail: require('../../assets/avatars/navigator/navigator-thumbnail.png'),
    primaryColor: '#0F766E',
    accentColor: '#5EEAD4',
  },
  STRATEGIST: {
    id: 'strategist',
    name: 'The Strategist',
    description: 'Calculated and wise - plans every move carefully',
    calmVideo: require('../../assets/avatars/strategist/strategist-calm.mp4'),
    actionVideo: require('../../assets/avatars/strategist/strategist-action.mp4'),
    thumbnail: require('../../assets/avatars/strategist/strategist-thumbnail.png'),
    primaryColor: '#7C3AED',
    accentColor: '#C4B5FD',
  },
  ADVOCATE: {
    id: 'advocate',
    name: 'The Advocate',
    description: 'Passionate and determined - fights for justice',
    calmVideo: require('../../assets/avatars/advocate/advocate-calm.mp4'),
    actionVideo: require('../../assets/avatars/advocate/advocate-action.mp4'),
    thumbnail: require('../../assets/avatars/advocate/advocate-thumbnail.png'),
    primaryColor: '#DC2626',
    accentColor: '#FCA5A5',
  },
};

export const ACTION_TRIGGERS = {
  SUBSTAGE_COMPLETE: 'substage_complete',
  STAGE_COMPLETE: 'stage_complete',
  DAILY_BONUS: 'daily_bonus',
  ACHIEVEMENT: 'achievement',
  MILESTONE: 'milestone',
};
