export const AVATARS = {
  CAPTAIN: {
    id: 'captain',
    name: 'The Advocate',
    description: 'Passionate and determined - fights for your justice',
    calmVideo: require('../../assets/avatars/captain/captain-calm.mp4'),
    calmVideoWeb: '/videos/avatars/captain-calm.mp4',
    thumbnail: require('../../assets/avatars/captain/captain-thumbnail.png'),
    thumbnailWeb: '/videos/avatars/captain-thumbnail.png',
    primaryColor: '#1E40AF',
    accentColor: '#60A5FA',
  },
  NAVIGATOR: {
    id: 'navigator',
    name: 'Lady Justice',
    description: 'Fair and balanced - upholds truth and righteousness',
    calmVideo: require('../../assets/avatars/navigator/navigator-calm.mp4'),
    calmVideoWeb: '/videos/avatars/navigator-calm.mp4',
    thumbnail: require('../../assets/avatars/navigator/navigator-thumbnail.png'),
    thumbnailWeb: '/videos/avatars/navigator-thumbnail.png',
    primaryColor: '#0F766E',
    accentColor: '#5EEAD4',
  },
  STRATEGIST: {
    id: 'strategist',
    name: 'The Paralegal',
    description: 'Organized and thorough - manages every detail expertly',
    calmVideo: require('../../assets/avatars/strategist/strategist-calm.mp4'),
    calmVideoWeb: '/videos/avatars/strategist-calm.mp4',
    thumbnail: require('../../assets/avatars/strategist/strategist-thumbnail.png'),
    thumbnailWeb: '/videos/avatars/strategist-thumbnail.png',
    primaryColor: '#7C3AED',
    accentColor: '#C4B5FD',
  },
  ADVOCATE: {
    id: 'advocate',
    name: 'The Judge',
    description: 'Wise and authoritative - guides you with experience',
    calmVideo: require('../../assets/avatars/advocate/advocate-calm.mp4'),
    calmVideoWeb: '/videos/avatars/advocate-calm.mp4',
    thumbnail: require('../../assets/avatars/advocate/advocate-thumbnail.png'),
    thumbnailWeb: '/videos/avatars/advocate-thumbnail.png',
    primaryColor: '#DC2626',
    accentColor: '#FCA5A5',
  },
  POLLY: {
    id: 'polly',
    name: 'Polly the Parrot',
    description: 'The Eternal Optimist. Always on your side',
    calmVideo: require('../../assets/avatars/polly/polly-calm.mp4'),
    calmVideoWeb: '/videos/avatars/polly-calm.mp4',
    thumbnail: require('../../assets/avatars/polly/polly-thumbnail.png'),
    thumbnailWeb: '/videos/avatars/polly-thumbnail.png',
    primaryColor: '#22C55E',
    accentColor: '#86EFAC',
  },
};

export const ACTION_TRIGGERS = {
  SUBSTAGE_COMPLETE: 'substage_complete',
  STAGE_COMPLETE: 'stage_complete',
  DAILY_BONUS: 'daily_bonus',
  ACHIEVEMENT: 'achievement',
  MILESTONE: 'milestone',
};
