import React from 'react';
import { Text, Platform } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';

const iconMap = {
  'home': '🏠',
  'arrow-left': '◀️',
  'arrow-right': '▶️',
  'close': '✕',
  'check': '✓',
  'check-circle': '✅',
  'check-circle-outline': '☑️',
  'check-all': '✔️',
  'plus': '➕',
  'minus': '➖',
  'delete': '🗑️',
  'delete-sweep': '🧹',
  'calendar': '📅',
  'calendar-month': '📆',
  'calendar-week': '🗓️',
  'calendar-star': '⭐',
  'calendar-check': '✅',
  'calendar-plus': '📅',
  'calendar-clock': '⏰',
  'calendar-blank': '📋',
  'calendar-blank-outline': '📋',
  'calendar-multiple': '📅',
  'calendar-remove': '❌',
  'clock-outline': '🕐',
  'clock-time-four-outline': '🕓',
  'account': '👤',
  'account-group': '👥',
  'account-circle': '👤',
  'account-off': '🚫',
  'account-search': '🔎',
  'doctor': '👨‍⚕️',
  'medical-bag': '💼',
  'hospital-building': '🏥',
  'scale-balance': '⚖️',
  'gavel': '🔨',
  'briefcase-off': '💼',
  'anchor': '⚓',
  'skull-crossbones': '☠️',
  'information': 'ℹ️',
  'bell-outline': '🔔',
  'bell': '🔔',
  'email-outline': '📧',
  'email': '📧',
  'message-text-outline': '💬',
  'message-text': '💬',
  'note-text': '📝',
  'content-save': '💾',
  'upload': '📤',
  'download': '📥',
  'cog': '⚙️',
  'block-helper': '🚫',
  'magnify': '🔍',
  'close-circle': '❌',
  'chevron-up': '▲',
  'chevron-down': '▼',
  'chevron-left': '◀',
  'chevron-right': '▶',
  'map-marker': '📍',
  'cellphone-link': '📱',
  'cellphone-off': '📵',
  'history': '📜',
  'format-list-bulleted': '📋',
  'clipboard-text': '📋',
  'heart-pulse': '❤️',
  'radioactive': '☢️',
  'dots-horizontal': '•••',
  'file-document': '📄',
  'file-document-outline': '📄',
  'alert': '⚠️',
  'alert-circle': '⚠️',
  'alert-circle-outline': '⚠️',
  'star': '⭐',
  'star-outline': '☆',
  'heart': '❤️',
  'heart-outline': '♡',
  'send': '📤',
  'refresh': '🔄',
  'sync': '🔄',
  'eye': '👁️',
  'eye-off': '🙈',
  'lock': '🔒',
  'lock-open': '🔓',
  'menu': '☰',
  'dots-vertical': '⋮',
  'pencil': '✏️',
  'edit': '✏️',
  'trash-can': '🗑️',
  'trash-can-outline': '🗑️',
  'phone': '📞',
  'phone-outline': '📞',
  'link': '🔗',
  'share': '↗️',
  'share-variant': '↗️',
  'logout': '🚪',
  'login': '🔑',
  'help-circle': '❓',
  'help-circle-outline': '❓',
  'currency-usd': '💵',
  'cash': '💰',
  'credit-card': '💳',
  'bank': '🏦',
  'filter': '🔽',
  'filter-outline': '🔽',
  'sort': '↕️',
  'sort-ascending': '↑',
  'sort-descending': '↓',
  'file-upload': '📤',
  'file-download': '📥',
  'folder': '📁',
  'folder-open': '📂',
  'image': '🖼️',
  'camera': '📷',
  'video': '🎬',
  'microphone': '🎤',
  'volume-high': '🔊',
  'volume-off': '🔇',
  'play': '▶️',
  'pause': '⏸️',
  'stop': '⏹️',
  'skip-next': '⏭️',
  'skip-previous': '⏮️',
  'compass': '🧭',
  'navigation': '🧭',
  'flag': '🚩',
  'bookmark': '🔖',
  'bookmark-outline': '🔖',
  'tag': '🏷️',
  'trophy': '🏆',
  'medal': '🎖️',
  'gift': '🎁',
  'treasure-chest': '📦',
  'pirate': '🏴‍☠️',
  'ship-wheel': '☸️',
  'sword-cross': '⚔️',
};

const CrossPlatformIcon = ({ name, size = 24, color = '#fff', style }) => {
  if (Platform.OS === 'web') {
    const emoji = iconMap[name] || '•';
    return (
      <Text style={[{ fontSize: size * 0.9, color, textAlign: 'center' }, style]}>
        {emoji}
      </Text>
    );
  }
  
  return <MaterialCommunityIcons name={name} size={size} color={color} style={style} />;
};

export default CrossPlatformIcon;
